version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: social-network-app:0.1
    container_name: social_network_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - app-data:/app/data
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  app-data:
    driver: local
  mongo-data:
    driver: local